run:
    build-tags:
        - meteor_robot
        - mage

linters:
    enable:
        - revive
        - misspell

linters-settings:
    staticcheck:
        checks: ["all","-ST1000","-ST1020","-S1008","-ST1003","-SA1029","-ST1001","-ST1021","-SA9003","-ST1015","-ST1012"]

    revive:
        ignoreGeneratedHeader: true
        severity: warning
        confidence: 0.8
        errorCode: 0
        warningCode: 0
        exclude:
            - ./test/...
            - ./scripts/...
        rule:
            - name: blank-imports
            - name: dot-imports
            - name: error-return
            - name: error-strings
            - name: error-naming
            - name: if-return
            - name: range
            - name: receiver-naming
            - name: time-naming
            - name: errorf
            - name: unreachable-code
            - name: redefines-builtin-id
            - name: atomic
            - name: banned
              arguments:
                - Ω
                - Σ
                - σ
            - name: call-to-gc
            - name: confusing-naming
            - name: datarace
            - name: deep-exit
            - name: defer
            - name: duplicated-imports
            - name: function-result
              arguments:
                - 4
            - name: function
              arguments:
                - 1000
                - 0
            - name: get-return
            - name: imports-blacklist
            - name: import-shadowing
            - name: modifies-parameter
            - name: modifies-value-receiver
            - name: optimize-operands-order
            - name: range-val-in-closure
            - name: range-val-address
            - name: string-of-int
            - name: struct-tag
            - name: string-format
            - name: time-equal
            - name: unconditional-recursion
            - name: waitgroup-by-value
